# Generated by Django 6.0.7 on 2026-08-23 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('location', models.TextField()),
                ('is_public', models.BooleanField()),
                ('is_inperson', models.BooleanField()),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='seminar_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seminars', to='core.category')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_seminars', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_seminars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
