# Generated by Django 4.2.30 on 2026-06-10 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.TextField(null=True)),
                ('price', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='seminar_image/')),
                ('is_public', models.BooleanField()),
                ('is_inperson', models.BooleanField()),
                ('location', models.TextField()),
                ('session_date', models.DateField()),
                ('session_time_start', models.TimeField()),
                ('session_time_end', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
