# Generated by Django 4.2.30 on 2026-06-10 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='participant',
        ),
        migrations.AlterField(
            model_name='seminar',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seminar',
            name='participant',
            field=models.ManyToManyField(related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
