# Generated by Django 4.2.30 on 2026-06-10 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_seminar_participant_alter_seminar_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
