# Generated by Django 6.0.7 on 2026-07-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_seminar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
