# Generated by Django 6.0.7 on 2026-07-12 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seminar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
