# Generated by Django 4.2.30 on 2026-06-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seminar_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='participant',
            new_name='participants',
        ),
    ]
