# Generated by Django 6.0.7 on 2026-09-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_seminar_organization_organizationmember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='updated_at',
        ),
    ]
