# Generated by Django 6.0.7 on 2026-07-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_seminar_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seminars', to='core.category'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_seminars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_seminars', to=settings.AUTH_USER_MODEL),
        ),
    ]
