# Generated by Django 6.0.7 on 2026-07-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_seminar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
