# Generated by Django 6.0.7 on 2026-07-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_default_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='discription',
            new_name='description',
        ),
    ]
