# Generated by Django 6.0.7 on 2026-09-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organizationmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='max_participants',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
