# Generated by Django 6.0.7 on 2026-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_seminar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default_seminar_image.png', upload_to='seminar_image/'),
        ),
    ]
