# Generated by Django 6.0.7 on 2026-07-16 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_discription_seminar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
