# Generated by Django 6.0.7 on 2026-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_seminar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, upload_to='seminar_image/'),
        ),
    ]
