# Generated by Django 6.0.7 on 2026-08-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seminar_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
