# Generated by Django 6.0.7 on 2026-08-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seminar_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='session_time_end',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='session_time_start',
        ),
        migrations.AddField(
            model_name='seminar',
            name='session_end',
            field=models.DateTimeField(default='2026-08-19T10:44'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='session_start',
            field=models.DateTimeField(default='2026-08-19T08:44'),
            preserve_default=False,
        ),
    ]
