# Generated by Django 6.0.7 on 2026-08-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_seminar',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.seminar'),
        ),
    ]
