# Generated by Django 6.0.7 on 2026-08-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_favorite_seminar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_seminar',
            new_name='favorite_seminars',
        ),
    ]
