# Generated by Django 6.0.7 on 2026-08-26 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificatinos', to=settings.AUTH_USER_MODEL),
        ),
    ]
