# Generated by Django 4.2.30 on 2026-07-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('IR', 'Iran'), ('TR', 'Turkey'), ('AZ', 'Azerbaijan')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('IR', 'Iran'), ('TR', 'Turkey'), ('AZ', 'Azerbaijan')], max_length=2, null=True),
        ),
    ]
