# Generated by Django 6.0.7 on 2026-08-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_notification_recipent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
