# Generated by Django 4.2.30 on 2026-07-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_city_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('TEH', 'Tehran'), ('TBZ', 'Tabriz'), ('MSH', 'Mashhad')], max_length=3, null=True),
        ),
    ]
