# Generated by Django 6.0.7 on 2026-09-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organization_organizationmember_organization_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='members',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.RemoveConstraint(
            model_name='organizationmember',
            name='unique_organization_member',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
    ]
