# Generated by Django 6.0.7 on 2026-09-19 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_notification_notification_type_and_more'),
        ('core', '0006_organizationmembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'organization'), name='unique_pending_organization_invitation'),
        ),
    ]
