# Generated by Django 6.0.7 on 2026-09-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_organizationinvitation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organizationinvitation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('invitation', 'Invitation'), ('ads', 'Advertisements')], default='normal', max_length=30),
        ),
    ]
